# Generated by Django 4.1.7 on 2023-03-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emp_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="hire_date",
            field=models.DateField(null=True),
        ),
    ]
