# Generated by Django 4.1.7 on 2023-03-03 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emp_app", "0002_alter_employee_hire_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="phones",
            new_name="phone",
        ),
    ]
