# Generated by Django 4.1.7 on 2023-03-04 09:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("emp_app", "0005_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="like",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
