# Generated by Django 4.1.7 on 2023-03-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emp_app", "0006_post_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(default=None, max_length=240),
            preserve_default=False,
        ),
    ]
